/**
 * @Course: SDEV 350 ~ Java Programming II
 * @JFrame:             Berwin_Week7
 * @Author Name:        Bobby Erwin <bobby@bobanahalf.com>
 * @Assignment Name:    berwin_week7
 * @Date:               Feb 26, 2015
 * @Description:        Push and Pop
 *
 * ------------------------------------------------------------
 * Change log
 * User Date Description -------- ----------
 * --------------------------------------- *
 *
 * ------------------------------------------------------------ *
 */

package berwin_week7;

// Imports

import java.awt.Color;
import java.util.Stack;


/**
 *
 * @author Bobby Erwin <bobby@bobanahalf.com>
 */
public class Berwin_Week7 extends javax.swing.JFrame {

    // class fields
    private final Stack st = new Stack();
    
    /** Creates new form Berwin_Week7 */
    public Berwin_Week7() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblPush = new javax.swing.JLabel();
        colonPush = new javax.swing.JLabel();
        lblPop = new javax.swing.JLabel();
        colonPop = new javax.swing.JLabel();
        lblStack = new javax.swing.JLabel();
        colonStack = new javax.swing.JLabel();
        txtPush = new javax.swing.JFormattedTextField();
        txtPop = new javax.swing.JFormattedTextField();
        btnPush = new javax.swing.JButton();
        btnPop = new javax.swing.JButton();
        txtStack = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(311, 206));
        setMinimumSize(new java.awt.Dimension(311, 206));

        pnlMain.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Stack Collection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), Color.BLUE)); // NOI18N
        pnlMain.setName("pnlMain"); // NOI18N

        lblPush.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPush.setText("Push Item");
        lblPush.setName("lblPush"); // NOI18N

        colonPush.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colonPush.setText(":");
        colonPush.setName("colonPush"); // NOI18N

        lblPop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPop.setText("Pop Item");
        lblPop.setName("lblPop"); // NOI18N

        colonPop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colonPop.setText(":");
        colonPop.setName("colonPop"); // NOI18N

        lblStack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStack.setText("Stack");
        lblStack.setName("lblStack"); // NOI18N

        colonStack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colonStack.setText(":");
        colonStack.setName("colonStack"); // NOI18N

        txtPush.setNextFocusableComponent(btnPush);

        txtPop.setNextFocusableComponent(btnPop);

        btnPush.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPush.setText("Push");
        btnPush.setName("btnPush"); // NOI18N
        btnPush.setNextFocusableComponent(txtPop);
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        btnPop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPop.setText("Pop");
        btnPop.setName("btnPop"); // NOI18N
        btnPop.setNextFocusableComponent(btnExit);

        txtStack.setFocusable(false);
        txtStack.setName("txtStack"); // NOI18N

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPush)
                    .addComponent(lblPop)
                    .addComponent(lblStack))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colonPush, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colonPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colonStack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStack)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPop, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txtPush))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPush, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPush)
                    .addComponent(colonPush)
                    .addComponent(btnPush)
                    .addComponent(txtPush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPop)
                    .addComponent(colonPop)
                    .addComponent(btnPop)
                    .addComponent(txtPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStack)
                    .addComponent(colonStack)
                    .addComponent(txtStack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setName("btnExit"); // NOI18N
        btnExit.setNextFocusableComponent(txtPush);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        st.push(txtPush.getText());
        txtStack.setText(st.toString());
    }//GEN-LAST:event_btnPushActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Berwin_Week7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Berwin_Week7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Berwin_Week7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Berwin_Week7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Berwin_Week7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JLabel colonPop;
    private javax.swing.JLabel colonPush;
    private javax.swing.JLabel colonStack;
    private javax.swing.JLabel lblPop;
    private javax.swing.JLabel lblPush;
    private javax.swing.JLabel lblStack;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JFormattedTextField txtPop;
    private javax.swing.JFormattedTextField txtPush;
    private javax.swing.JTextField txtStack;
    // End of variables declaration//GEN-END:variables

}
